Feat/student experience
Geupjo-Hackathon/KoreanTiger-BE pull request #5
Opened 2023-09-20 11:59 UTC by SeungchanKKK

StudentLms part controller service facade repository setup

2023-09-20 12:15 UTC, 0AndWild requested changes

2023-09-20 12:15 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/controller/student/StudentLmsController.java
> +@RequestMapping("v1")
v1 앞에 / 가 빠져있음

2023-09-20 12:15 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/controller/student/StudentLmsController.java
> +        public ApiResponse StudentExperienceResponse(@Parameter(description = "학생Id") @RequestParam(value = "studentID", required = false) Long studentId) {
해당 api 는 학생이 로그인 된 상태에서 호출되는 api 이기 때문에 인증된 유저의 정보를 서버에서 가져와서 응답을 내려주는 방식으로 가는게 좋아보임!

즉, mock user를 만들어서 contextHoler에서 인증된 유저의 정보를 가져오는 시나리오로 진행하는 것이 좀 더 좋을 것 같다는 생각

2023-09-20 12:15 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/controller/student/StudentLmsController.java
> +        public ApiResponse StudentExperienceResponse(@Parameter(description = "학생Id") @RequestParam(value = "studentID", required = false) Long studentId) {
StudentExperienceResponse <- 메서드 이름인데 대문자로 시작하고 있음

2023-09-20 12:15 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/repository/MemberRepository.java
> +public interface MemberRepository extends JpaRepository<Member, Long> {
@Repository 어노테이션 누락

2023-09-20 12:15 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +@RequiredArgsConstructor
@RequiredArgsConstructor 가 @Service 어노테이션보다 밑에 있는게 좋을 것 같음

2023-09-20 12:15 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/facade/StudentLmsFacade.java
> +
@Component 어노테이션을 붙여서 bean으로 등록해서 사용하는 것이 좋아보임

2023-09-20 14:50 UTC, Rojojun reviewed
두 분 멋있어용.... Perfecto!!!

2023-09-20 14:50 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/service/facade/StudentLmsFacade.java
> +
오... 관념차이겠지만 @Component 어노테이션 보다 @Service 어노테이션을 붙이는건 어떤지?!? 이미 Service가 나뉘어져 있어서 Component로 bean등록 나누어서 하는건가~~~?!?!? 😃

2023-09-20 14:50 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/service/facade/Facade.java
> +
혹시 이 클래스는 Facade에 대한 관심분리를 하기 위함인가요~~!?!? 그렇다면 너무 멋진거 같아서여!!

2023-09-20 14:50 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/service/facade/Facade.java
> +
아니군여... 지우셨군옄ㅋㅋㅋㅋㅋ

2023-09-20 14:50 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/entity/Member.java
> +public class Member extends BaseEntity {
👍

2023-09-21 13:13 UTC, 0AndWild requested changes

2023-09-21 13:13 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +        EducationProfile profile = educationProfileRepository.findByMemberId(student.getId());
해당 학생 Id로 EducationProfile을 찾았을 때 데이터가 존재하지 않아 internal server error가 나올 수 있습니다. Optional로 감싸서 educationProfile이 존재하지 않을 경우에 대한 예외 처리를 해주어주는 것이 좋아보입니다.

2023-09-21 13:13 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +        //학교랭킹 50위 레벨 및 경험치순으로 정렬
랭킹은 유저 프로필 api와 분리를 하는 것이 좋을 것 같습니다.
랭킹 데이터는 school과 total로 나뉘어지므로 클라이언트로부터 랭킹 타입을 enum으로 받아 필요한 데이터만 응답해주는 것이 조금 더 좋을 것 같다는 생각이 듭니다.

2023-09-21 13:13 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +        List<EducationProfile>educationHistories= educationProfileRepository.findTop50ByOrderByLevelExperience();
educationProfile과 educationHistory는 서로 다른 엔티티 인데 여기서는 프로필정보를 불러오는 것이니 변수명은 educationProfiles 또는 profiles 정도가 적당해 보입니다.

2023-09-21 13:13 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +        ArrayList<StudentRankingDto>inSchoolRankingBoard = new ArrayList<>();
타입과 변수명 사이에 공백을 하나 넣어주는 것이 좋아보입니다.

2023-09-21 13:13 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +        List<EducationProfile>educationHistories= educationProfileRepository.findTop50ByOrderByLevelExperience();
타입, 변수명, = 사이에 공백 부탁드립니다.
전체적으로 변경사항에 대해 코드 포멧팅, 정렬, 임포트 최적화를 한 번 진행해주시는 게 좋을 것 같습니다.

2023-09-21 13:13 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +                    memberRepository.findById(eachProfile.getMemberId()).orElseThrow(()-> new CustomException(ErrorCode.NOTMATCH_USER_EXCEPTION)).getName(),
생성자 안에서 조회로직을 넣는 것 보단 밖으로 빼주는 것이 좋아보입니다. 생성자 안에서 조회를 하다보니 name라는 String타입에 맞추기 위해 throw를 던졌음에도 .getName을 호출하여 에러코드의 메세지를 학생이름 필드에 넣어주는 상황이 나옵니다.

2023-09-21 13:13 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +                    memberRepository.findById(eachProfile.getMemberId()).orElseThrow(()-> new CustomException(ErrorCode.NOTMATCH_USER_EXCEPTION)).getName(),
이부분은 for문 안에서 db connection을 하나씩 지속적으로 소모하는 것 보다 educationHistories에 있는 memberId를 모아서 한번에 In절로 묶어 meber를 한번에 조회하고 병합해주는 방식이 좋을 것 같습니다.

2023-09-22 01:50 UTC, 0AndWild requested changes
리뷰 사항 1개와 db에서 꺼내오는 로직은 에러 던지지 말고 mock 데이터로 바꿔서 응답해주는 방식으로 바꾸면 될 것 같습니다. 안그럼 프론트쪽에서 테스트 때 응답을 못받아서 힘들 것 같아요.
 
+ 지금 main이랑 충돌나고 있으니 로컬에서 메인 한번 당겨서 머지하고 충동해결 후

2023-09-22 01:50 UTC, 0AndWild commented on src/main/java/com/geupjo/koreantiger/enums/StudentProfileTitle.java
> +    private String titleName;
titleName을 final 필드로 선언하는게 조금 더 좋아보입니다.

그리고 이건 선택 사항이지만 아래의 생성자와 getTitleName을 롬복을 이용하면 조금 더 깔끔해지지 않을까 합니다

2023-09-22 02:09 UTC, SeungchanKKK commented on src/main/java/com/geupjo/koreantiger/enums/StudentProfileTitle.java
> +    private String titleName;
리뷰내용 반영했습니다

2023-09-22 03:10 UTC, 0AndWild submitted a review, later dismissed
👍

2023-09-22 03:12 UTC, 0AndWild approved these changes

2023-09-22 03:12 UTC, 0AndWild reviewed
👍

2023-09-22 03:13 UTC, 0AndWild approved these changes

2023-09-22 03:14 UTC, 0AndWild requested changes
👍

2023-09-22 03:14 UTC, 0AndWild submitted a review, later dismissed

2023-09-22 03:16 UTC, 0AndWild approved these changes

2023-09-22 03:16 UTC, 0AndWild reviewed
👍

2023-09-22 03:20 UTC, 0AndWild approved these changes

2023-09-22 03:21 UTC, 0AndWild approved these changes
👍

2023-09-22 03:22 UTC, merged