Feat : student one year education histories
Geupjo-Hackathon/KoreanTiger-BE pull request #8
Opened 2023-09-21 18:57 UTC by 0AndWild

- 현재 날짜 기준 지난 1년간의 학습 데이터 API 추가

2023-09-21 19:39 UTC, SeungchanKKK reviewed
리뷰 남겼습니다

2023-09-21 19:39 UTC, SeungchanKKK commented on src/main/java/com/geupjo/koreantiger/controller/student/StudentLmsController.java
> +    @GetMapping("/education/histories/")
경로명 studentLms 로 차후 통일해서 이용하는것이 좋아보입니다
ex) studentLms/history , studentLms/ranking

2023-09-21 19:39 UTC, SeungchanKKK commented on src/main/java/com/geupjo/koreantiger/controller/student/StudentLmsController.java
> +    public ApiResponse<StudentHistoryResponseDto> studentEducationHistories() {
Api 명세가 누락되어있습니다.
머지이전에 추가하면될것같습니다

2023-09-21 19:39 UTC, SeungchanKKK commented on src/main/java/com/geupjo/koreantiger/dto/response/StudentHistoryResponseDto.java
> +            LocalDate date,
LearningHistory 에 learningTimeGrade 이외에 learningtime 을 xx시간xx분 처럼 시간 을 추가하여
캘린더에 마우스를 올릴때 상세 정보를 확인할수있게 해주면 더좋을것같습니다

2023-09-21 19:46 UTC, SeungchanKKK requested changes

2023-09-21 19:46 UTC, SeungchanKKK commented on src/main/java/com/geupjo/koreantiger/dto/response/StudentExpProfileDto.java
> +        ArrayList<StudentRankingDto>inSchoolRankingBoard,
랭킹과 프로필 부분 dto 변경했으니 차후 머지할때 수정들어가면될것같습니다

2023-09-22 03:53 UTC, Rojojun reviewed
너무 잘한당....
👍

2023-09-22 03:53 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/common/jpa/BaseEntity.java
> +@AllArgsConstructor
생성자를 통해서 값을 주입받을 수도 있으니까~ 생성자는 필요없어보이긴한데~~ 굿굿!

2023-09-22 03:53 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/entity/Member.java
> +@NoArgsConstructor
accesslevel을 지정해주면 캡슐화에 도움될겁니다요~~!

2023-09-22 03:53 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/enums/LearningTimeGrade.java
> +    public static LearningTimeGrade convert(long learningTime) {
👍

2023-09-22 03:53 UTC, Rojojun commented on src/main/java/com/geupjo/koreantiger/service/StudentLmsService.java
> +        System.out.println(duration);
혹시 이게 info성 로깅인가용~~ 그렇다면 @Slf4j에 로깅을 쓰는게 어떤가여~~?!? 추후에 로깅 모니터링(ELK, 그라파나)도 log.xml등으로 설정해서 가져올 수 있구 시스템 콘솔로 찍는거보다 성능이 더 좋아여~~!

2023-09-22 04:18 UTC, Rojojun approved these changes

2023-09-22 04:22 UTC, SeungchanKKK approved these changes

2023-09-22 04:22 UTC, SeungchanKKK commented on src/main/java/com/geupjo/koreantiger/controller/student/StudentLmsController.java
> +    public ApiResponse<StudentHistoryResponseDto> studentEducationHistories() {
굿

2023-09-22 04:22 UTC, merged